---
abstract: 'Lets tests validate code which interacts with files without them '
author:
  - 'Todd Rinaldo <toddr@cpanel.net>'
build_requires:
  Test2::Bundle::Extended: '0'
  Test2::Plugin::NoWarnings: '0'
  Test2::Tools::Explain: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-MockFile
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
version: '0.001'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
